######################################################################
# Automatically generated by qmake (1.07a) Tue Jul 27 22:20:19 2004
######################################################################


# Input












































































TEMPLATE	= app
LANGUAGE	= C++

CONFIG	+= qt warn_on release


SOURCES	+= main.cpp
FORMS	= form1.ui

